### PR TITLE
ACME V2 and DNS challenge

### PR DESCRIPTION
**Pull request by avonwyss**
This is a preparation for supporting wildcard hosts (which IIS 2016 now fully supports as well); see my comment in #17 

* Converted code to use ACME V2 protocol instead of V1
* Refactored challenge handling
* Added DNS challenge support with catch-all scheme
* Added simple SAN support (multiple hostnames are allowed when manually adding a host)
* Added certificate wildcard support

Migration from the current version and the HTTP-based challenges need some testing, but I think it should work fine.

Note: this PR includes the IDN changes

### CODE REVIEW

**Comment by ridercz** [comment]
Thank you for your work. I don't have time to work on AutoACME right now, but it seems you are doing what I should and I'm unable to. Could you please update the documentation as well? Regarding the newly added options like self-hosting, IDN, SAN certificates... I invited you as collaborator, so you should have direct access to wiki.

**Comment by avonwyss** [comment]
@ridercz You're welcome, the code (and project in general) was a great starting point for me - despite being a long-time IIS user I was not aware of the CCS before coming across AutoACME.

Regarding documentation, I did already document the self-hosted part in early september:
https://github.com/ridercz/AutoACME/wiki/AutoACME-in-a-web-farm-environment

How should we deal with the documentation versioning? Whatever I change in the documentation does not yet apply to the currently available release, making it out-of-sync.

**Comment by ridercz** [comment]
I think the best solution would be for me to release next version of AutoACME. Everything you changed only adds functionality and everything in the current documentation still stands, so it will work. Then you can write the documentation for functions to be included in the then current release. Sounds good?

**Comment by avonwyss** [comment]
Yes, that's fine for me. The new functionality is already summarized in the "web farm" document and I can then add more detailed info on dedicated pages.

Regarding the release, I successfully tested plain certificates, SAN certificates and mixed wildcard certificates with DNS and self-hosting fallback with `autoacme.exe`. However I did not test the file-based functionality or `iissync.exe`. I don't see a reason why it should be broken, but maybe you can quickly test this out in your environment (assuming that you're using these yourself)?

**Pull request merged**
