### PR TITLE
Support for self-hosted challenge

### PR DESCRIPTION
**Pull request by avonwyss**
I'm using AutoACME with a DFS-based (replicated) CCS with multiple IIS servers. However I want to run AutoACME (both for adding domains as well as for maintenance) on a backend server which does not have IIS installed, and I didn't want to create a IIS site for handling the challenges. Instead I have the AutoACME app self-host the challenge for the duration of the request - no dedicated web site or file involved.

This PR contains the following changes:
- Fix of broken AssemblyInfo files, addition of .editorconfig and ReShaper settings for formatting style
- Refactoring to consolidate the identical code parts of IisSync and Manager into the Core library
- Configurable HTTP.SYS-based self-hosting of challenge

Note: I have not touched the version; if you want to accept the PR you can either adjust it yourself or let me know which version number you want.

### CODE REVIEW

**Comment by ridercz** [comment]
Hello and thank you for your work. I pulled your code into a new branch `selfhost` and will take a look at it, as I need to understand some of the changes you made. 

Please note that in next few weeks I would be very busy, as I teach a lot of courses right now, so it will take some time till I get to it, so my reaction may not be as quick as I would like.

**Comment by avonwyss** [comment]
Thanks for the response. I did my best to be in line with the style and concepts of the existing codebase, looking forward to your comments (whenever that will be).

One thing I forgot to mention and which would have to go into the documentation is a self-hosting gotcha related to the Windows Firewall: https://stackoverflow.com/questions/17863294/c-sharp-httplistener-and-windows-firewall

**Comment by ridercz** [comment]
It would be generally good, if you would write some documentation about self-hosting scenario - how and when to use.

**Comment by avonwyss** [comment]
I actually wanted to write something, but since it is in the Github wiki I cannot directly contribute there. 

However, the usage scenario is quite simple: use this when you want to avoid setting up a dedicated website for the challenges. Everything else remains the same as before, the application just acts as HTTP server itself instead of writing a file for serving it with IIS. 

The benefit when used with a CCS on a network share (or even DFS with replication as in my case) is that you can run AutoACME on a host which does not have to be one of the web servers, it does not even have to have IIS installed. It just needs write access to the folder with the certificates (the web servers only need read access to the CCS folder/share).

**Comment by ridercz** [comment]
Sorry it took me so long to merge your request. I added you to collaborators so you should be able to add the documentation to wiki. Once you'll do it, I will create new release.

**Comment by avonwyss** [comment]
@ridercz Thanks, I added some documentation explaining when and how to use the self-hosting.

**Pull request merged**
